In [61]:
import numpy as np

def downsample_class_one(X, y, downsample_ratio):
    # Find indices of class 0 and class 1
    class_0_indices = np.where(y == 0)[0]
    class_1_indices = np.where(y == 1)[0]

    # Calculate the desired number of samples for class 1
    desired_samples = int(len(class_0_indices) * downsample_ratio)

    # Randomly select samples from class 1 without replacement
    downsampled_indices = np.random.choice(class_1_indices, size=desired_samples, replace=False)

    # Combine the downsampled class 1 samples with all class 0 samples
    downsampled_X = np.concatenate((X[class_0_indices], X[downsampled_indices]), axis=0)
    downsampled_y = np.concatenate((y[class_0_indices], y[downsampled_indices]), axis=0)

    return downsampled_X, downsampled_y

# Example usage
X = np.array([[1, 2, 3],
              [4, 5, 6],
              [7, 8, 9],
              [10, 11, 12],
              [13, 14, 15],
              [16, 17, 18]])

y = np.array([0, 0, 1, 1, 1, 1])

downsample_ratio = 0.5
downsampled_X, downsampled_y = downsample_class_one(X, y, downsample_ratio)

print(downsampled_X)
print(downsampled_y)


[[ 1  2  3]
 [ 4  5  6]
 [16 17 18]]
[0 0 1]


In [72]:
import numpy as np

def downsample_data(X, y, downsample_ratio, class_to_downsample):
    # Find indices of each class
    unique_classes = np.unique(y)
    class_indices = [np.where(y == cls)[0] for cls in unique_classes]
    
    # Calculate the desired number of samples for the class to downsample
    class_to_downsample_index = np.where(unique_classes == class_to_downsample)[0][0]
    class_to_downsample_indices = class_indices[class_to_downsample_index]
    desired_samples = int(len(class_to_downsample_indices) * downsample_ratio)
    
    # Randomly select samples from the class to downsample
    downsampled_indices = np.random.choice(class_to_downsample_indices, desired_samples, replace=False)
    
    # Gather indices of the other class
    other_class_index = 1 - class_to_downsample_index
    other_class_indices = class_indices[other_class_index]
    
    # Combine indices of both classes
    downsampled_indices = np.concatenate((downsampled_indices, other_class_indices))
    
    downsampled_X = X[downsampled_indices]
    downsampled_y = y[downsampled_indices]
    
    return downsampled_X, downsampled_y

# Example usage
X = np.array([[1, 2, 3],
              [4, 5, 6],
              [7, 8, 9],
              [10, 11, 12],
              [13, 14, 15],
              [16, 17, 18]])

y = np.array([0, 0, 1, 1, 1, 1])

downsample_ratio = 0.5
class_to_downsample = 1

downsampled_X, downsampled_y = downsample_data(X, y, downsample_ratio, class_to_downsample)

print(downsampled_X)
print(downsampled_y)


[[13 14 15]
 [16 17 18]
 [ 1  2  3]
 [ 4  5  6]]
[1 1 0 0]


In [1]:
import gdal